name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of dxf-checker are you running?
      placeholder: e.g. 1.0.0
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Use DXF file with '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output (use --verbose flag)
      render: shell

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g. Windows 11, Ubuntu 22.04, macOS 13
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: e.g. 3.9.5
    validations:
      required: true