[bumpver]
current_version = "2.0.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump: version {old_version} → {new_version}"
tag_message = "Release {new_version}"
tag_scope = "default"

[bumpver.file_patterns]
"dxf_checker/__init__.py" = [
    '__version__ = "{pep440_version}"'
]

[bumpver.git]
commit = true
tag = true
push = true