[bumpver]
current_version = "1.1.4"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump: version {old_version} → {new_version}"
tag_message = "Release {new_version}"
tag_scope = "default"
search = ["dxf_checker/__init__.py"]

[git]
tag = true
commit = true
push = true